export const CATEGORY = [
  {key: 0, name: '무기'},
  {key: 1, name: '방어구'},
  {key: 2, name: '장신구'},
  {key: 3, name: '소모용품'},
  {key: 4, name: '기타아이템'},
  {key: 5, name: '페트'},
]

export const ITEMS = [
  {key:1, category:2, name:'할아버지의 부적', thumbnail:'/images/item/001.jpg'},
  {key:2, category:4, name:'이상한 조개', thumbnail:'/images/item/002.jpg'},
  {key:3, category:0, name:'야무야무의 도끼', thumbnail:'/images/item/003.jpg'},
  {key:4, category:1, name:'의식의 모자', thumbnail:'/images/item/004.jpg'},
  {key:5, category:1, name:'의식의 갑옷', thumbnail:'/images/item/005.jpg'},
  {key:6, category:0, name:'의식의 곤봉', thumbnail:'/images/item/006.jpg'},
  {key:7, category:2, name:'진주 팔찌', thumbnail:'/images/item/007.jpg'},
  {key:8, category:3, name:'사톤가의 비약', thumbnail:'/images/item/008.jpg'},
  {key:9, category:4, name:'삼위일체의 구슬', thumbnail:'/images/item/009.jpg'},
  {key:10, category:2, name:'삼위일체(改)', thumbnail:'/images/item/010.jpg'},
  {key:11, category:2, name:'번개의 반지', thumbnail:'/images/item/011.jpg'},
  {key:12, category:2, name:'머슬링 귀걸이', thumbnail:'/images/item/012.jpg'},
  {key:13, category:2, name:'티아트의 대지', thumbnail:'/images/item/013.jpg'},
  {key:14, category:2, name:'바르의 바람', thumbnail:'/images/item/014.jpg'},
  {key:15, category:0, name:'흑룡의 발톱', thumbnail:'/images/item/015.jpg'},
  {key:16, category:3, name:'적색 큐브', thumbnail:'/images/item/016.jpg'},
  {key:17, category:3, name:'얼음성 레어 페트병', thumbnail:'/images/item/017.jpg'},
  {key:18, category:3, name:'얼음성 전리품 아이템', thumbnail:'/images/item/018.jpg'},
  {key:19, category:3, name:'레이드 문서', thumbnail:'/images/item/019.jpg'},
  {key:20, category:3, name:'과일 꾸러미', thumbnail:'/images/item/020.jpg'},
  {key:21, category:3, name:'성장 억제제', thumbnail:'/images/item/021.jpg'},
  {key:22, category:3, name:'얼음성 RP 페트병', thumbnail:'/images/item/022.jpg'},
  {key:23, category:2, name:'기계 심장', thumbnail:'/images/item/023.jpg'},
  {key:24, category:3, name:'기계무덤 전리품', thumbnail:'/images/item/024.jpg'},
  {key:25, category:3, name:'영혼의 서약', thumbnail:'/images/item/025.jpg'},
  {key:26, category:2, name:'골로스의 심장', thumbnail:'/images/item/026.jpg'},
  {key:27, category:3, name:'기계파편(風)', thumbnail:'/images/item/027.jpg'},
  {key:28, category:3, name:'기계파편(地)', thumbnail:'/images/item/028.jpg'},
  {key:29, category:3, name:'기계파편(火)', thumbnail:'/images/item/029.jpg'},
  {key:30, category:3, name:'기계파편(水)', thumbnail:'/images/item/030.jpg'},
  {key:31, category:4, name:'용을 부르는 피리(火)', thumbnail:'/images/item/031.jpg'},
  {key:32, category:4, name:'용을 부르는 피리(水)', thumbnail:'/images/item/032.jpg'},
  {key:33, category:4, name:'화룡의 손톱', thumbnail:'/images/item/033.jpg'},
  {key:34, category:4, name:'화룡의 뼛조각', thumbnail:'/images/item/034.jpg'},
  {key:35, category:4, name:'화룡의 가죽', thumbnail:'/images/item/035.jpg'},
  {key:36, category:4, name:'수룡의 비늘', thumbnail:'/images/item/036.jpg'},
  {key:37, category:4, name:'수룡의 발톱', thumbnail:'/images/item/037.jpg'},
  {key:38, category:4, name:'수룡의 가죽', thumbnail:'/images/item/038.jpg'},
  {key:39, category:3, name:'정령의 상자', thumbnail:'/images/item/039.jpg'},
  {key:40, category:3, name:'정령의 전리품', thumbnail:'/images/item/040.jpg'},
  {key:41, category:2, name:'정령의 반지(地)', thumbnail:'/images/item/041.jpg'},
  {key:42, category:2, name:'정령의 반지(水)', thumbnail:'/images/item/042.jpg'},
  {key:43, category:2, name:'정령의 반지(火)', thumbnail:'/images/item/043.jpg'},
  {key:44, category:2, name:'정령의 반지(風)', thumbnail:'/images/item/044.jpg'},
  {key:45, category:3, name:'보석 상자(중급)', thumbnail:'/images/item/045.jpg'},
  {key:46, category:3, name:'경험치 티켓(800,000Exp)', thumbnail:'/images/item/046.jpg'},
  {key:47, category:3, name:'칠흑의 정령 페트 병', thumbnail:'/images/item/047.jpg'},
  {key:48, category:3, name:'지옥의 증서', thumbnail:'/images/item/048.jpg'},
  {key:49, category:4, name:'지옥의 암석', thumbnail:'/images/item/049.jpg'},
  {key:50, category:2, name:'타우루스의 부적', thumbnail:'/images/item/050.jpg'},
  {key:51, category:1, name:'지옥의 투구', thumbnail:'/images/item/051.jpg'},
  {key:52, category:0, name:'삼수정 곤봉', thumbnail:'/images/item/052.jpg'},
  {key:53, category:2, name:'지옥의 전리품', thumbnail:'/images/item/053.jpg'},
  {key:54, category:1, name:'지옥견 털옷', thumbnail:'/images/item/054.jpg'},
  {key:55, category:2, name:'지옥의 반지', thumbnail:'/images/item/055.jpg'},
  {key:56, category:0, name:'지옥의 창', thumbnail:'/images/item/056.jpg'},
  {key:57, category:3, name:'지옥문 전리품', thumbnail:'/images/item/057.jpg'},
  {key:58, category:3, name:'지옥문 레어 페트병', thumbnail:'/images/item/058.jpg'},
  {key:59, category:4, name:'감정 구슬', thumbnail:'/images/item/059.jpg'},
  {key:60, category:4, name:'볼라', thumbnail:'/images/item/060.jpg'},
  {key:61, category:4, name:'골드볼라', thumbnail:'/images/item/061.jpg'},
  {key:62, category:3, name:'일반 큐브', thumbnail:'/images/item/062.jpg'},
  {key:63, category:3, name:'장인의 큐브', thumbnail:'/images/item/063.jpg'},
  {key:64, category:3, name:'고급 큐브', thumbnail:'/images/item/064.jpg'},
  {key:65, category:3, name:'챠밍허브농축액(10)', thumbnail:'/images/item/065.jpg'},
  {key:66, category:3, name:'벽청의 소라', thumbnail:'/images/item/066.jpg'},
  {key:67, category:3, name:'칸의 자루 (1번)', thumbnail:'/images/item/067.jpg'},
  {key:68, category:3, name:'칸의 자루 (2번)', thumbnail:'/images/item/068.jpg'},
  {key:69, category:3, name:'황금자루 (2번)', thumbnail:'/images/item/069.jpg'},
  {key:70, category:3, name:'황금자루 (3번)', thumbnail:'/images/item/070.jpg'},
  {key:71, category:2, name:'네메시스 팬던트', thumbnail:'/images/item/071.jpg'},
  {key:72, category:2, name:'영웅 팬던트', thumbnail:'/images/item/072.jpg'},
  {key:73, category:4, name:'쟈쟈 스튜', thumbnail:'/images/item/073.jpg'},
  {key:74, category:4, name:'샴기르의 동상조각', thumbnail:'/images/item/074.jpg'},
  {key:75, category:3, name:'포인트 문서', thumbnail:'/images/item/075.jpg'},
  {key:76, category:3, name:'명성 문서', thumbnail:'/images/item/076.jpg'},
  {key:77, category:3, name:'은빛 보물상자', thumbnail:'/images/item/077.jpg'},
  {key:78, category:3, name:'금빛 보물상자', thumbnail:'/images/item/078.jpg'},
  {key:79, category:3, name:'천상의 보물상자', thumbnail:'/images/item/079.jpg'},
  {key:80, category:0, name:'사냥꾼의 활', thumbnail:'/images/item/080.jpg'},
  {key:81, category:3, name:'랜덤 소재 상자 (소재9 상자)', thumbnail:'/images/item/081.jpg'},
  {key:82, category:2, name:'삼색 팔찌', thumbnail:'/images/item/082.jpg'},
  {key:83, category:3, name:'기술 확장권', thumbnail:'/images/item/083.jpg'},
  {key:84, category:2, name:'꼬미 변신토템', thumbnail:'/images/item/084.jpg'},  
  {key:85, category:3, name:'경험치 티켓 (2,000,000Exp)', thumbnail:'/images/item/085.jpg'},
  {key:86, category:3, name:'스테이크', thumbnail:'/images/item/086.jpg'},
  {key:87, category:2, name:'천상의 팔찌', thumbnail:'/images/item/087.jpg'},
  {key:88, category:3, name:'천상의 보물상자 페트 병', thumbnail:'/images/item/088.jpg'},
  {key:89, category:4, name:'석상 소재 1~3', thumbnail:'/images/item/089.jpg'},
  {key:90, category:4, name:'소재 보따리', thumbnail:'/images/item/090.jpg'},
  {key:91, category:2, name:'합성 토템 1~3', thumbnail:'/images/item/091.jpg'},
  {key:92, category:2, name:'합성 팔찌 4', thumbnail:'/images/item/092.jpg'},
  {key:93, category:2, name:'합성 반지 4', thumbnail:'/images/item/093.jpg'},
  {key:94, category:2, name:'합성 귀걸이 4', thumbnail:'/images/item/094.jpg'},
  {key:95, category:1, name:'합성 옷 9', thumbnail:'/images/item/095.jpg'},
  {key:96, category:1, name:'합성 갑옷 9', thumbnail:'/images/item/096.jpg'},
  {key:97, category:1, name:'합성 모자 9', thumbnail:'/images/item/097.jpg'},
  {key:98, category:1, name:'합성 투구 9', thumbnail:'/images/item/098.jpg'},
  {key:99, category:0, name:'합성 돌 9', thumbnail:'/images/item/099.jpg'},
  {key:100, category:0, name:'합성 돌도끼 9', thumbnail:'/images/item/100.jpg'},
  {key:101, category:0, name:'합성 부메랑 9', thumbnail:'/images/item/101.jpg'},
  {key:102, category:0, name:'합성 활 9', thumbnail:'/images/item/102.jpg'},
  {key:103, category:0, name:'합성 손톱 9', thumbnail:'/images/item/103.jpg'},
  {key:104, category:0, name:'합성 곤봉 9', thumbnail:'/images/item/104.jpg'},
  {key:105, category:0, name:'합성 도끼 9', thumbnail:'/images/item/105.jpg'},
  {key:106, category:0, name:'합성 창 9', thumbnail:'/images/item/106.jpg'},
  {key:107, category:3, name:'접속 보상상자', thumbnail:'/images/item/107.jpg'},
  {key:108, category:0, name:'백호의 장갑', thumbnail:'/images/item/108.jpg'},
  {key:109, category:1, name:'백호의 모자', thumbnail:'/images/item/109.jpg'},
  {key:110, category:1, name:'백호의 옷', thumbnail:'/images/item/110.jpg'},
  {key:111, category:2, name:'하트 목걸이', thumbnail:'/images/item/111.jpg'},
  {key:112, category:2, name:'얼룩우리 토템', thumbnail:'/images/item/112.jpg'},
  {key:113, category:4, name:'이상한 조개', thumbnail:'/images/item/113.jpg'},
  {key:114, category:3, name:'보물 보따리', thumbnail:'/images/item/114.jpg'},
  {key:115, category:3, name:'페트 통조림', thumbnail:'/images/item/115.jpg'},
  {key:116, category:2, name:'대지의 깃털', thumbnail:'/images/item/116.jpg'},
  {key:117, category:2, name:'수창의 조개', thumbnail:'/images/item/117.jpg'},
  {key:118, category:2, name:'바람의 팔찌', thumbnail:'/images/item/118.jpg'},
  {key:119, category:2, name:'불사조의 깃털', thumbnail:'/images/item/119.jpg'},
  {key:120, category:0, name:'마쥬의 도끼', thumbnail:'/images/item/120.jpg'},
  {key:121, category:0, name:'마쥬의 창', thumbnail:'/images/item/121.jpg'},
  {key:122, category:0, name:'마쥬의 곤봉', thumbnail:'/images/item/122.jpg'},
  {key:123, category:1, name:'꿈의 모자', thumbnail:'/images/item/123.jpg'},
  {key:124, category:1, name:'꿈의 옷', thumbnail:'/images/item/124.jpg'},
  {key:125, category:2, name:'꿈의 하프', thumbnail:'/images/item/125.jpg'},
  {key:126, category:4, name:'체크 스톤', thumbnail:'/images/item/126.jpg'},
  {key:127, category:2, name:'월광의 팔찌', thumbnail:'/images/item/127.jpg'},
  {key:128, category:1, name:'수호정령 얀 미트의 옷', thumbnail:'/images/item/128.jpg'},
  {key:129, category:2, name:'후르도의 하프', thumbnail:'/images/item/129.jpg'},
  {key:130, category:2, name:'기노의 팔찌', thumbnail:'/images/item/130.jpg'},
  {key:131, category:2, name:'리논의 목걸이', thumbnail:'/images/item/131.jpg'},
  {key:132, category:2, name:'기로스의 반지', thumbnail:'/images/item/132.jpg'},
  {key:133, category:2, name:'보로스의 피리', thumbnail:'/images/item/133.jpg'},
  {key:134, category:1, name:'용의 갑옷', thumbnail:'/images/item/134.jpg'},
  {key:135, category:1, name:'용의 옷', thumbnail:'/images/item/135.jpg'},
  {key:136, category:0, name:'용의 창', thumbnail:'/images/item/136.jpg'},
  {key:137, category:3, name:'마론의 포도', thumbnail:'/images/item/137.jpg'},
  {key:138, category:3, name:'사톤가의 비약', thumbnail:'/images/item/138.jpg'},
  {key:139, category:0, name:'한의 도끼', thumbnail:'/images/item/139.jpg'},
  {key:140, category:3, name:'VP 포인트 티켓', thumbnail:'/images/item/140.jpg'},
  {key:141, category:3, name:'환포 클리어 문서', thumbnail:'/images/item/141.jpg'},
  {key:142, category:3, name:'파멸의 세트 보따리', thumbnail:'/images/item/142.jpg'},
  {key:143, category:3, name:'바람의 세트 보따리', thumbnail:'/images/item/143.jpg'},
  {key:144, category:0, name:'파멸의 창', thumbnail:'/images/item/144.jpg'},
  {key:145, category:1, name:'파멸의 옷', thumbnail:'/images/item/145.jpg'},
  {key:146, category:1, name:'파멸의 투구', thumbnail:'/images/item/146.jpg'},
  {key:147, category:0, name:'바람의 창', thumbnail:'/images/item/147.jpg'},
  {key:148, category:1, name:'바람의 투구', thumbnail:'/images/item/148.jpg'},
  {key:149, category:1, name:'바람의 갑옷', thumbnail:'/images/item/149.jpg'},
  {key:150, category:3, name:'초기화 구슬', thumbnail:'/images/item/150.jpg'},
  {key:151, category:3, name:'닉네임 변경권', thumbnail:'/images/item/151.jpg'},
  {key:152, category:3, name:'Lv140 달성 페트 병', thumbnail:'/images/item/152.jpg'},
  {key:153, category:0, name:'산타 장갑', thumbnail:'/images/item/153.jpg'},
  {key:154, category:1, name:'산타 모자', thumbnail:'/images/item/154.jpg'},
  {key:155, category:1, name:'산타 옷', thumbnail:'/images/item/155.jpg'},
  {key:156, category:0, name:'광석의 창', thumbnail:'/images/item/156.jpg'},
  {key:157, category:1, name:'광석의 투구', thumbnail:'/images/item/157.jpg'},
  {key:158, category:1, name:'광석의 갑옷', thumbnail:'/images/item/158.jpg'},
  {key:159, category:3, name:'정장툰가 변경권', thumbnail:'/images/item/159.jpg'},
  {key:160, category:3, name:'페트 병(기계문명)', thumbnail:'/images/item/160.jpg'},
  {key:161, category:3, name:'페트 병(꼬마용)', thumbnail:'/images/item/161.jpg'},
  {key:162, category:3, name:'생명의 알[고오다]', thumbnail:'/images/item/162.jpg'},
  {key:163, category:3, name:'생명의 알[아마란]', thumbnail:'/images/item/163.jpg'},
  {key:164, category:3, name:'아마란 토템', thumbnail:'/images/item/164.jpg'},
  {key:165, category:3, name:'고오다 토템(1일)', thumbnail:'/images/item/165.jpg'},
  {key:166, category:3, name:'아이템 자판기[판매종료]', thumbnail:'/images/item/166.jpg'},
  {key:167, category:3, name:'페트 자판기', thumbnail:'/images/item/167.jpg'},
  {key:168, category:4, name:'문울프의 손톱', thumbnail:'/images/item/168.jpg'},
  {key:169, category:4, name:'문울프 소탕 증서', thumbnail:'/images/item/169.jpg'},
  {key:170, category:3, name:'진 푸푸 변신토템(30일)', thumbnail:'/images/item/170.jpg'},
  {key:171, category:3, name:'청록 큐브', thumbnail:'/images/item/171.jpg'},
  {key:172, category:3, name:'진 반기노 토템(30일)', thumbnail:'/images/item/172.jpg'},
  {key:173, category:3, name:'진 베르가 토템(30일)', thumbnail:'/images/item/173.jpg'},
  {key:174, category:0, name:'카루타나의 활[風]', thumbnail:'/images/item/174.jpg'},
  {key:175, category:0, name:'쟈쟈의 활[地]', thumbnail:'/images/item/175.jpg'},
  {key:176, category:0, name:'마리너스의 활[水]', thumbnail:'/images/item/176.jpg'},
  {key:177, category:0, name:'샴기르의 활[火]', thumbnail:'/images/item/177.jpg'},
  {key:178, category:3, name:'보물의 방 깃털', thumbnail:'/images/item/178.jpg'},
  {key:179, category:1, name:'헤티아의 머리 장식', thumbnail:'/images/item/179.jpg'},
  {key:180, category:1, name:'초신성 갑옷', thumbnail:'/images/item/180.jpg'},
  {key:181, category:0, name:'헤티아의 빛나는 창', thumbnail:'/images/item/181.jpg'},
  {key:182, category:2, name:'풍신의 주머니', thumbnail:'/images/item/182.jpg'},
  {key:183, category:2, name:'대지의 심장', thumbnail:'/images/item/183.jpg'},
  {key:184, category:2, name:'불사조의 정신', thumbnail:'/images/item/184.jpg'},
  {key:185, category:3, name:'페트 병(아스타로)', thumbnail:'/images/item/185.jpg'},
  {key:186, category:3, name:'헤티아의 보물', thumbnail:'/images/item/186.jpg'},
  {key:187, category:2, name:'벽청의 보석 [30일]', thumbnail:'/images/item/187.jpg'},
  {key:188, category:2, name:'진홍의 보석 [30일]', thumbnail:'/images/item/188.jpg'},
  {key:189, category:2, name:'유리의 보석[30일]', thumbnail:'/images/item/189.jpg'},
  {key:190, category:2, name:'천지의 보석 [30일]', thumbnail:'/images/item/190.jpg'},
  {key:191, category:3, name:'페트 병(개인듀얼)', thumbnail:'/images/item/191.jpg'},
  {key:192, category:0, name:'정령왕의 활', thumbnail:'/images/item/192.jpg'},
  {key:193, category:3, name:'나무메달', thumbnail:'/images/item/193.jpg'},
  {key:194, category:1, name:'늪지의 투구', thumbnail:'/images/item/194.jpg'},
  {key:195, category:1, name:'늪지의 갑옷', thumbnail:'/images/item/195.jpg'},
  {key:196, category:0, name:'늪지의 창', thumbnail:'/images/item/196.jpg'},
  {key:197, category:0, name:'타이거 스피어', thumbnail:'/images/item/197.jpg'},
  {key:198, category:3, name:'지옥의 돌', thumbnail:'/images/item/198.jpg'},
  {key:199, category:2, name:'사육가의 귀걸이', thumbnail:'/images/item/199.jpg'},
  {key:200, category:3, name:'토끼 변신 토템', thumbnail:'/images/item/200.jpg'},
  {key:201, category:1, name:'토끼 모자', thumbnail:'/images/item/201.jpg'},
  {key:202, category:1, name:'토끼 옷', thumbnail:'/images/item/202.jpg'},
  {key:203, category:0, name:'토끼 장갑', thumbnail:'/images/item/203.jpg'},
  {key:204, category:3, name:'경험치 문서 [200만]', thumbnail:'/images/item/204.jpg'},
  {key:205, category:3, name:'경험치 문서 [500만]', thumbnail:'/images/item/205.jpg'},
  {key:206, category:3, name:'불량소년 패드(히든)', thumbnail:'/images/item/206.jpg'},
  {key:207, category:3, name:'한가위 페트병', thumbnail:'/images/item/207.jpg'},
  {key:208, category:3, name:'레오딘 페트병', thumbnail:'/images/item/208.jpg'},
  {key:209, category:3, name:'암흑골로스 페트병', thumbnail:'/images/item/209.jpg'},
  {key:210, category:0, name:'불꽃 장궁', thumbnail:'/images/item/210.jpg'},
  {key:211, category:3, name:'기계 파편(暗)', thumbnail:'/images/item/211.jpg'},
  {key:212, category:3, name:'삼위일체의 심장', thumbnail:'/images/item/212.jpg'},
  {key:213, category:2, name:'삼위일체[眞]', thumbnail:'/images/item/213.jpg'},
  {key:214, category:1, name:'태풍의 투구', thumbnail:'/images/item/214.jpg'},
  {key:215, category:1, name:'태풍의 갑옷', thumbnail:'/images/item/215.jpg'},
  {key:216, category:0, name:'태풍의 창', thumbnail:'/images/item/216.jpg'},
  {key:217, category:0, name:'공포의 도끼', thumbnail:'/images/item/217.jpg'},
  {key:218, category:2, name:'이라의 불꽃', thumbnail:'/images/item/218.jpg'},
  {key:219, category:0, name:'열공의 도끼', thumbnail:'/images/item/219.jpg'},
  {key:220, category:1, name:'얼음 옷', thumbnail:'/images/item/220.jpg'},
  {key:221, category:1, name:'얼음 투구', thumbnail:'/images/item/221.jpg'},
  {key:222, category:3, name:'크리스마스 토큰', thumbnail:'/images/item/222.jpg'},
  {key:223, category:3, name:'악몽의 방 깃털', thumbnail:'/images/item/223.jpg'},
  {key:224, category:3, name:'크리스마스 패키지', thumbnail:'/images/item/224.jpg'},
  {key:225, category:3, name:'크리스마스 페트 상자', thumbnail:'/images/item/225.jpg'},
  {key:226, category:3, name:'캐릭터 보따리[토큰 상점]', thumbnail:'/images/item/226.jpg'},
  {key:227, category:3, name:'캐릭터 보따리[크리스마스 핫타임]', thumbnail:'/images/item/227.jpg'},
  {key:228, category:3, name:'마몽의 상자', thumbnail:'/images/item/228.jpg'},
  {key:229, category:3, name:'눈꽃 사탕 (2,000,000Exp)', thumbnail:'/images/item/229.jpg'},
  {key:230, category:3, name:'얼음 찹쌀떡 (10,000,000Exp)', thumbnail:'/images/item/230.jpg'},
  {key:231, category:2, name:'불사조의 깃털[火]', thumbnail:'/images/item/231.jpg'},
  {key:232, category:2, name:'대지의 깃털[地]', thumbnail:'/images/item/232.jpg'},
  {key:233, category:2, name:'수창의 조개[水]', thumbnail:'/images/item/233.jpg'},
  {key:234, category:2, name:'바람의 팔찌[風]', thumbnail:'/images/item/234.jpg'},
  {key:235, category:0, name:'냉동 황새치', thumbnail:'/images/item/235.jpg'},
  {key:236, category:3, name:'설날 바구니', thumbnail:'/images/item/236.jpg'},
  {key:237, category:3, name:'설날 신년 상자', thumbnail:'/images/item/237.jpg'},
  {key:238, category:3, name:'설날 토큰', thumbnail:'/images/item/238.jpg'},
  {key:239, category:1, name:'뱀의 갑옷[地/水/火/風]', thumbnail:'/images/item/239.jpg'},
  {key:240, category:1, name:'뱀의 투구[地/水/火/風]', thumbnail:'/images/item/240.jpg'},
  {key:241, category:2, name:'영웅의 신물', thumbnail:'/images/item/241.jpg'},
  {key:242, category:2, name:'영광의 신물', thumbnail:'/images/item/242.jpg'},
  {key:243, category:2, name:'지옥의 신물', thumbnail:'/images/item/243.jpg'},
  {key:244, category:3, name:'얼음의 돌', thumbnail:'/images/item/244.jpg'},
  {key:245, category:3, name:'암흑 헤티아의 전리품', thumbnail:'/images/item/245.jpg'},
  {key:246, category:4, name:'보물 지도', thumbnail:'/images/item/246.jpg'},
  {key:247, category:4, name:'보물 상자(하~상)', thumbnail:'/images/item/247.jpg'},
  {key:248, category:3, name:'대게 찜', thumbnail:'/images/item/248.jpg'},
  {key:249, category:3, name:'경험치 축적의 열매(진화/환생)', thumbnail:'/images/item/249.jpg'},
  {key:250, category:3, name:'경험치 축적의 열매(레이드)', thumbnail:'/images/item/250.jpg'},
  {key:251, category:3, name:'진화/환생의 열매', thumbnail:'/images/item/251.jpg'},
  {key:252, category:3, name:'환생 초기화 구슬', thumbnail:'/images/item/252.jpg'},
  {key:253, category:3, name:'보석[風]', thumbnail:'/images/item/253.jpg'},
  {key:254, category:3, name:'보석[地]', thumbnail:'/images/item/254.jpg'},
  {key:255, category:3, name:'보석[火]', thumbnail:'/images/item/255.jpg'},
  {key:256, category:3, name:'속성의 정수', thumbnail:'/images/item/256.jpg'},
  {key:257, category:3, name:'킹콩의 전리품', thumbnail:'/images/item/257.jpg'},
  {key:258, category:3, name:'라엘리언의 전리품', thumbnail:'/images/item/258.jpg'},
  {key:259, category:2, name:'라엘리언의 심장', thumbnail:'/images/item/259.jpg'},
  {key:260, category:2, name:'라엘리언의 귀걸이', thumbnail:'/images/item/260.jpg'},
  {key:261, category:3, name:'고대 오형제 페트 병(선택)', thumbnail:'/images/item/261.jpg'},
  {key:262, category:3, name:'고대 오형제 페트 병(랜덤)', thumbnail:'/images/item/262.jpg'},
  {key:263, category:0, name:'거인의 곤봉', thumbnail:'/images/item/263.jpg'},
  {key:264, category:1, name:'고대의 투구', thumbnail:'/images/item/264.jpg'},
  {key:265, category:2, name:'고대의 목걸이', thumbnail:'/images/item/265.jpg'},
  {key:266, category:3, name:'빛의 정수', thumbnail:'/images/item/266.jpg'},
  {key:267, category:3, name:'이벤트 토큰(가정의 달)', thumbnail:'/images/item/267.jpg'},
  {key:268, category:3, name:'이벤트 볼라(가정의달)', thumbnail:'/images/item/268.jpg'},
  {key:269, category:2, name:'이벤트 토템(어린호랑이)', thumbnail:'/images/item/269.jpg'},
  {key:270, category:3, name:'시간의 토템', thumbnail:'/images/item/270.jpg'},
  {key:271, category:3, name:'가정의 달 페트상자', thumbnail:'/images/item/271.jpg'},
  {key:272, category:3, name:'가정의 달 선물상자', thumbnail:'/images/item/272.jpg'},
  {key:273, category:3, name:'이벤트 활 상자(선택)', thumbnail:'/images/item/273.jpg'},
  {key:274, category:2, name:'풍신의 주머니[眞]', thumbnail:'/images/item/274.jpg'},
  {key:275, category:2, name:'대지의 심장[眞]', thumbnail:'/images/item/275.jpg'},
  {key:276, category:2, name:'불사조의 정신[眞]', thumbnail:'/images/item/276.jpg'},
  {key:277, category:2, name:'현무 토템 [30일]', thumbnail:'/images/item/277.jpg'},
  {key:278, category:2, name:'주작 토템 [30일]', thumbnail:'/images/item/278.jpg'},
  {key:279, category:2, name:'풍백 토템 [30일]', thumbnail:'/images/item/279.jpg'},
  {key:280, category:3, name:'기계 파편(明)', thumbnail:'/images/item/280.jpg'},
  {key:281, category:3, name:'맘모스 쿠폰[1차]', thumbnail:'/images/item/281.jpg'},
  {key:282, category:3, name:'메가 고르돈의 전리품', thumbnail:'/images/item/282.jpg'},
  {key:283, category:3, name:'메가 카키의 전리품', thumbnail:'/images/item/283.jpg'},
  {key:284, category:3, name:'열정의 물약', thumbnail:'/images/item/284.jpg'},
  {key:285, category:3, name:'속성 석 (地)', thumbnail:'/images/item/285.jpg'},
  {key:286, category:3, name:'속성 석 (水)', thumbnail:'/images/item/286.jpg'},
  {key:287, category:3, name:'속성 석 (火)', thumbnail:'/images/item/287.jpg'},
  {key:288, category:3, name:'속성 석 (風)', thumbnail:'/images/item/288.jpg'},
  {key:289, category:3, name:'생명의 열매', thumbnail:'/images/item/289.jpg'},
  {key:290, category:3, name:'생명의 열매[환생]', thumbnail:'/images/item/290.jpg'},
  {key:291, category:3, name:'페가수스 페트병', thumbnail:'/images/item/291.jpg'},
  {key:292, category:3, name:'신비의 수정', thumbnail:'/images/item/292.jpg'},
  {key:293, category:3, name:'샴기르 촌장 토템(15일)', thumbnail:'/images/item/293.jpg'},
  {key:294, category:2, name:'복권 아가씨 토템(15일)', thumbnail:'/images/item/294.jpg'},
  {key:295, category:2, name:'동메달', thumbnail:'/images/item/295.jpg'},
  {key:296, category:2, name:'은메달', thumbnail:'/images/item/296.jpg'},
  {key:297, category:2, name:'금메달', thumbnail:'/images/item/297.jpg'},
  {key:298, category:3, name:'페트 병(섬머)', thumbnail:'/images/item/298.jpg'},
  {key:299, category:3, name:'한가위 곶감', thumbnail:'/images/item/299.jpg'},
  {key:300, category:3, name:'토끼 토템 [1일]/[5일]', thumbnail:'/images/item/300.jpg'},
  {key:301, category:3, name:'히든 패드 상자', thumbnail:'/images/item/301.jpg'},
  {key:302, category:1, name:'호수의 투구', thumbnail:'/images/item/302.jpg'},
  {key:303, category:1, name:'호수의 갑옷', thumbnail:'/images/item/303.jpg'},
  {key:304, category:0, name:'호수의 창', thumbnail:'/images/item/304.jpg'},

]



// var num = 285
// var text = '';
// $($('.is_tmb').get().reverse()).each(function(i) {
//     var name = $(this).children('.ngeb').text()
//     var key = num + i;
//     var category = $(this).find('> .info > span:first-child > b').text()
//     switch(category) {
//         case '무기':
//             category = 0
//             break;
//         case '방어구':
//           category = 1
//           break;
//         case '장신구':
//           category = 2
//           break;   
//         case '소모용품':
//           category = 3
//           break;
//         case '기타아이템':
//           category = 4
//           break;
//         case '세트아이템':
//           category = 5
//           break;    
//     }
//     var url;
//     if (url > 99) {
//       url = key;
//     } else if (url > 9) {
//       url = '0' + key;
//     } else {
//       url = '00' + key;
//     }
//     var thumbnail = `/images/item/${url}.jpg`;
//     text += (`{key:${key}, category:${category}, name:'${name}', thumbnail:'${thumbnail}'},\n`)
// })
// console.log(text);



// var num = 285;
// $($('.tmb').get().reverse()).each(function(i) {
//     var url =  this.src;
//     var download = num + i;
//     if (download > 99) {
//         download = download + '.jpg'
//     } else if (download > 9) {
//         download = '0' + download + '.jpg'
//     } else {
//         download = '00' + download + '.jpg'
//     }
//     setTimeout(() => {
//             var link = document.createElement('a');
//             link.href = url;
//             link.download = download;
//             document.body.appendChild(link);
//             link.click();
//             document.body.removeChild(link);
//     }, i * 200)
// })